language: node_js
node_js:
  - 12.12.0

before_script:
  - git config --local user.name "$GIT_NAME"
  - git config --local user.email "$GIT_EMAIL"

script:
  - npm run test
  - npm run babel
  - mkdir style
  - cp src/style/theme_light.css style/theme_light.css
  - cp src/style/theme_dark.css style/theme_dark.css

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      tags: true
      branch: master
